const availableKeywords = [
    { name: "Anesthesia Complications" },
    { name: "Heart Disease" },
    { name: "Arrhythmia" },
    { name: "Hypertension" },
    { name: "Skin Cancer" },
    { name: "Acne" },
    { name: "Eczema" },
    { name: "Trauma" },
    { name: "Heart Attack" },
    { name: "Stroke" },
    { name: "Diabetes" },
    { name: "Thyroid Disorders" },
    { name: "Obesity" },
    { name: "Common Cold" },
    { name: "Flu" },
    { name: "High Blood Pressure" },
    { name: "Gastritis" },
    { name: "Ulcers" },
    { name: "Irritable Bowel Syndrome" },
    { name: "Appendicitis" },
    { name: "Hernia" },
    { name: "Gallstones" },
    { name: "Anemia" },
    { name: "Leukemia" },
    { name: "Hemophilia" },
    { name: "Influenza" },
    { name: "HIV/AIDS" },
    { name: "Malaria" },
    { name: "Pneumonia" },
    { name: "Diabetes" },
    { name: "Hypertension" },
    { name: "Kidney Stones" },
    { name: "Chronic Kidney Disease" },
    { name: "Urinary Tract Infection" },
    { name: "Stroke" },
    { name: "Alzheimer's Disease" },
    { name: "Epilepsy" },
    { name: "Pregnancy Complications" },
    { name: "Endometriosis" },
    { name: "Breast Cancer" },
    { name: "Breast Cancer" },
    { name: "Lung Cancer" },
    { name: "Colon Cancer" },
    { name: "Cataracts" },
    { name: "Glaucoma" },
    { name: "Macular Degeneration" },
    { name: "Fractures" },
    { name: "Arthritis" },
    { name: "ACL Tear" },
    { name: "Sinusitis" },
    { name: "Ear Infections" },
    { name: "Tonsillitis" },
    { name: "Ear Infections" },
    { name: "Asthma" },
    { name: "ADHD" },
    { name: "Muscle Strain" },
    { name: "Joint Pain" },
    { name: "Spinal Cord Injury" },
    { name: "Breast Augmentation" },
    { name: "Rhinoplasty" },
    { name: "Liposuction" },
    { name: "Depression" },
    { name: "Anxiety Disorders" },
    { name: "Schizophrenia" },
    { name: "Asthma" },
    { name: "Chronic Obstructive Pulmonary Disease (COPD)" },
    { name: "Pneumonia" },
    { name: "X-ray Imaging" },
    { name: "CT Scan" },
    { name: "MRI Scan" },
    { name: "Rheumatoid Arthritis" },
    { name: "Osteoarthritis" },
    { name: "Lupus" },
    { name: "Urinary Tract Infection" },
    { name: "Kidney Stones" },
    { name: "Prostate Cancer" }
  ];
  export default availableKeywords;