import { createSlice, PayloadAction } from '@reduxjs/toolkit';
import { createSelector } from 'reselect';

// Define the interface for the UserState
export interface UserState {
  userId: string;
  userName: string;
  userEmail: string;
}

// Define the initial state using that type
const initialState: UserState = {
  userId: '',
  userName: '',
  userEmail: ''
};

// Create the user slice
export const userSlice = createSlice({
  name: 'user',
  initialState,
  reducers: {
    // Define a setUser action that takes a UserState as payload
    setUser: (state, action: PayloadAction<UserState>) => {
      state.userId = action.payload.userId;
      state.userName = action.payload.userName;
      state.userEmail = action.payload.userEmail;
    }
  }
});

// Export the action creators generated by createSlice
export const { setUser } = userSlice.actions;

// Define a selector to get the user state
export const getUserSelector = createSelector(
  (state: { user: UserState }) => state.user,
  (user) => user
);

// Export the reducer to be included in the store
export default userSlice.reducer;
